### ISSUE TITLE
"你的节点"是什么格式的

### ISSUE THREAD

**Issue by YBYCS** [70loKirin/Pretty-Derby-clash#1]
我想问下就是第二部中你的节点是什么格式的 是指机场中节点的名称还是什么呢
其次url是否要用引号括起来
谢谢

**Comment by YBYCS** [comment]
试了下 貌似节点就是名字 不用加引号 订阅链接要加引号
然后报错是因为 第二部中的DMM是没有分配组来处理 应该分配组(和赛马一样 起名叫DMM)
或者直接删去DMM部分?
        - DOMAIN-SUFFIX,dmm-extension.com,DMM
        - DOMAIN-SUFFIX,dmm.com,DMM
        - DOMAIN-SUFFIX,dmm.co.jp,DMM
        - DOMAIN-SUFFIX,dmmgames.com,DMM
        - DOMAIN-SUFFIX,dmm.hk,DMM

**Comment by magic5al** [comment]
> 试了下 貌似节点就是名字 不用加引号 订阅链接要加引号 然后报错是因为 第二部中的DMM是没有分配组来处理 应该分配组(和赛马一样 起名叫DMM) 或者直接删去DMM部分? - DOMAIN-SUFFIX,dmm-extension.com,DMM - DOMAIN-SUFFIX,dmm.com,DMM - DOMAIN-SUFFIX,dmm.co.jp,DMM - DOMAIN-SUFFIX,dmmgames.com,DMM - DOMAIN-SUFFIX,dmm.hk,DMM

看起来你的第一个问题已经解决了，请问你第二个问题的报错是在哪里报错的

**Comment by YBYCS** [comment]
其实第二个也解决了 报错就是说你第二部不是有
- DOMAIN-SUFFIX,dmm-extension.com,DMM
- DOMAIN-SUFFIX,dmm.com,DMM
- DOMAIN-SUFFIX,dmm.co.jp,DMM
- DOMAIN-SUFFIX,dmmgames.com,DMM
- DOMAIN-SUFFIX,dmm.hk,DMM
但是这个DMM是没有分组的然后报错了
不过最后还是没能找到可有的节点就是了

**Comment by magic5al** [comment]
> 

能用就行能用就行  规则这块我是在nga上面cp下来的

**Comment by Latomoyocarl** [comment]
> > 
> 
> 能用就行能用就行 规则这块我是在nga上面cp下来的

我也在名称那里跌过跤，建议 Owner 把 readme 里面“你的节点”改成“你的节点1/2/3的名称”或者更加明了的格式或者注释
